#!/bin/sh /etc/rc.common


START=62

boot() { 
	/data/funjsq/bin/funjsq.sh init

	funjsq_accType=`cat /data/funjsq/config/values/funjsq_accType`
	funjsq_accArea=`cat /data/funjsq/config/values/funjsq_accArea`

	funjsq_status=`cat /data/funjsq/config/values/funjsq_status`

	[ "x$funjsq_status" == "x1" -o "x$funjsq_status" == "x2"  ] && {
		/data/funjsq/bin/funjsq.sh start "$funjsq_accType" "$funjsq_accArea" & 
	}
}
